### ISSUE TITLE
Create Core Game Component (quick play)

### ISSUE THREAD

**Issue by kennethbolin** [jrs-coding-school/winter-2023-group-project#6]
### User Story

As a player, I want to play a trivia game of randomized general knowledge questions that is 3 minutes long so that I can keep myself entertained.

### Acceptance criteria

**UI**
- [ ] implement a check if the user is logged in, if they are not logged in redirect to /login
- [x] Create a route “/gamemodes”
- [x] Create a link on the homepage that will route to “/gamemodes”
- [ ] Create a fetch request for getting questions from API
- [ ] Create a timer component that counts down based on game rules provided. See #16
- [ ] Create a component to display the question and 4 multiple choice answers
- [ ] When the correct answer is selected, let the user know they were correct by highlighting green
- [ ] When the incorrect answer is selected, let the user know they were incorrect by highlighting red
- [ ] when the timer runs out, end the game. See #22

**API**

- [ ] Create a route “/trivia-questions”
- [ ] Select random questions from the database see #29
- [ ] return the questions, correct answer, incorrect answer, category, difficulty

### Wireframe
![game wireframe](https://user-images.githubusercontent.com/121542304/226692296-b39d75b8-7922-46a1-be14-579e46ed1be0.jpg)
